### ISSUE TITLE
[Feature Request] Trigger matching branch builds.

### ISSUE THREAD

**Issue by jhernandezme** [drone-plugins/drone-downstream#19]
Trigger matching branch builds.

For example:
I have different projects that use git-flow for example and have direct co-dependency between environments by branch naming qa->qa, dev->dev,  

Whenever a build happens in `ProjectA` in `dev` branch I also want to target the `dev` branch in the downstream `ProjectB` and so on for different branches

$MATCH would indicate that the name of the branch should be taken from `DRONE_COMMIT_BRANCH`
```yaml
pipeline:
  downstream:
    image: plugins/downstream
    server: https://ci.example.com
    repositories:
      - octocat/Hello-World@$MATCH
      - octocat/Spoon-Knife@$MATCH
    when:
      event: push
      branch: [master, dev, qa]
      success: true
```

I'm happy to open a PR.
