### ISSUE TITLE
[proposal] trigger downstream with several key/value

### ISSUE THREAD

**Issue by ozbillwang** [drone-plugins/drone-downstream#29]
For my understanding, trigger `drone-downstream` is to run a similar `drone build start` command via api.

Which I need: 

1) need exitra feature to trigger with several `--param key=value`. These `key/values` can be generated from preview steps in same `.drone.yml`
2) Support `drone deploy` as well (#25), because both `drone build` and `drone deploy` supports `--param key=value` and I do need to trigger downsteam with `drone deploy` directly. 

My questions are, why not use a drone-cli container to do the job directly, more than write a seperate Go plugin? It will support any new future features automatically from  new version of drone cli `drone build/deploy` 

So:

1) Can Drone team lead to build `drone-cli` as official image when new version released? It will be better to make the old version available as well. 

2) Rewrite this plugin (or create a new one) to accept key/value and support `deploy` as well

New plugin usage will be similar as below:

```
notify:
  downstream:
    image: plugins/downstream
    server: https://ci.example.com
    type: [build|deploy]
    param: 
      key1: ${varialbe1}
      key2: ${varialbe2}
    repositories:
      - octocat/Hello-World@develop
```

I am happy to work on this, but the thing to stop me is, how to transfer variables from preview step to this plugin (varialbe1 and varialbe2)?
