### ISSUE TITLE
Ability to trigger branch same current

### ISSUE THREAD

**Issue by Valeran86** [drone-plugins/drone-downstream#49]
Drone have variable $DRONE_BRANCH. In some cases (f.e. release & develop CI tree) it would be great to set branch in repositories like that:
```
  trigger_next_stage_release:
    image: plugins/downstream
    server: https://drone.ts-t.ru
    fork: true
    repositories:
      - SomeOwner/some-project@$DRONE_BRANCH
    secrets: [ downstream_token ]
    when:
      event: [ tag, push ]
      branch: [ release/*, release*, master ]
```
But now it doesn't work:
```
time="2019-01-10T05:14:25Z" level=fatal msg="Error: unable to get latest build for SomeOwner/some-project@$DRONE_BRANCH.\n"
```

**Comment by Valeran86** [comment]
May be solution is https://github.com/drone-plugins/drone-downstream/pull/50?

**Comment by Valeran86** [comment]
@tboerger, @techknowlogick Hi, guys. Can you review that issue & pull request?

**Comment by Valeran86** [comment]
Thank you @tboerger! It's my fault that i forgot to try with `{}`. Your suggestion really works.
```
  trigger_next_stage_release:
    image: plugins/downstream
    server: https://drone.ts-t.ru
    fork: true
    repositories:
      - SomeOwner/some-project@${DRONE_BRANCH}
    secrets: [ downstream_token ]
    when:
      event: [ tag, push ]
      branch: [ release/*, release*, master ]
```
That config correctly starts new build:
```
Starting new build 80 for SomeOwner/some-project@release-RC.
```
