### ISSUE TITLE
Branch / build no is ignored

### ISSUE THREAD

**Issue by smnbbrv** [drone-plugins/drone-downstream#59]
The latest `develop` branch build has a number 3. 

First of all, when I did not have a build on master it was

```
time="2019-04-17T09:14:09Z" level=fatal msg="Error: unable to get latest build for owner/repo-name@develop.\n"
```

I created a build on `master` branch, it got number 4.

Then I try both

```yml
kind: pipeline
name: default

steps:
  - name: name
    when:
      branch:
        - master
        - develop
    image: plugins/downstream
    settings:
      server: https://drone.example.com
      token:
        from_secret: drone_token
      fork: true
      repositories:
        - owner/repo-name@develop
```

```
Starting new build 5 for owner/repo-name@develop.
```

and 

```yml
kind: pipeline
name: default

steps:
  - name: name
    when:
      branch:
        - master
        - develop
    image: plugins/downstream
    settings:
      server: https://drone.example.com
      token:
        from_secret: drone_token
      fork: true
      repositories:
        - owner/repo-name@3
```

```
Starting new build 6 for owner/repo-name@3.
```

But both trigger the master build and not develop. So, I assume the @3 and @develop is simply ignored
