### ISSUE TITLE
downstream not working as plugin

### ISSUE THREAD

**Issue by kjschnei001** [drone-plugins/drone-downstream#6]
Downloading the downstream plugin docker container is working for me as follows:
```
docker run -i plugins/drone-downstream <<EOF
{
    "system": {
        "link_url": "http://drone.server.com"
    },
    "vargs": {
        "repositories": [
            "org/repo"
        ],
        "Server": "http://drone.server.com",
        "token": <TOKEN>
    }
}
EOF
```

but I am unable to trigger a downstream build using the same arguments in drone:
```
notify:
  downstream:
    server: "http://drone.server.com"
    repositories:
      - org/repo
    token: $$DRONE_API_TOKEN
    when:
      event: push
      branch: master
      success: true
```

There is no error output from the build either. I have confirmed the notify step is working by adding a hipchat notification step.
